dubbo:
  application:
    name: user-provider
#    version: 1.0.0
#    logger: log4j2
  registry:
    address: 127.0.0.1
    protocol: zookeeper
    port: 2181
  protocol:
    port: -1
    name: dubbo
#    host: 10.113.23.50
  monitor:
    protocol: registry
#  provider:
#    timeout: 3000
#    version: 1.0.0


