version: "3.5"
services:
  dubbo-admin:
    image: com.docker/dubbo-admin
    container_name: dubbo-admin
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "7011:7001"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net

networks:
  net:
    driver: bridge
    name: cm_net